/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        navy: {
          50: "#F4F6F2",
          100: "#F4F6F2",
          200: "#E6EAE4",
          300: "#C6CDC6",
          400: "#9AA39B",
          500: "#6A726C",
          600: "#555C56",
          700: "#2E352F",
          800: "#1B1F1C",
          850: "#171B18",
          900: "#121513",
          950: "#0B0D0C",
        },
        indigo: {
          300: "#D6FF5C",
          400: "#C9F73A",
          500: "#C9F73A",
          600: "#B4E02E",
        },
        signal: {
          success: "#3DDC84",
          danger: "#FF4D4F",
          warning: "#FFB02E",
          info: "#C9F73A",
        },
        field: "#0B0D0C",
        panel: "#121513",
        overpanel: "#171B18",
        "panel-2": "#1B1F1C",
        surface: "#121513",
        wash: "#171B18",
        paper: "#0B0D0C",
        ink: "#F4F6F2",
        "ink-soft": "#C6CDC6",
        "ink-muted": "#9AA39B",
        "ink-faint": "#6A726C",
        line: "#232824",
        "line-strong": "#2E352F",
        accent: {
          DEFAULT: "#C9F73A",
          soft: "#D6FF5C",
          hover: "#B4E02E",
        },
        volt: {
          DEFAULT: "#C9F73A",
          soft: "#D6FF5C",
          dark: "#B4E02E",
        },
        success: "#3DDC84",
        danger: "#FF4D4F",
        warning: "#FFB02E",
        gold: "#F5C842",
        silver: "#B0B0B0",
        bronze: "#C47B3A",
        orange: "#FF8C42",
        subject: {
          bio: "#3DDB6F",
          chem: "#F5C842",
          phys: "#6B9CFF",
          math: "#FF6B6B",
        },
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          "SF Pro Text",
          "Segoe UI",
          "Roboto",
          "Inter",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        display: ["Anton", "Impact", "Arial Black", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "SF Mono", "Menlo", "Consolas", "monospace"],
      },
      spacing: {
        "18": "4.5rem",
        "88": "22rem",
      },
      borderRadius: {
        "4xl": "2rem",
      },
      boxShadow: {
        card: "0 1px 0 rgba(255,255,255,0.04), 0 12px 28px -12px rgba(0,0,0,0.7)",
        pop: "0 2px 0 rgba(255,255,255,0.05), 0 24px 60px -20px rgba(0,0,0,0.85)",
      },
      animation: {
        "fade-in": "fadeIn 0.25s ease-out",
        "slide-up": "slideUp 0.25s ease-out",
        "slide-down": "slideDown 0.25s ease-out",
        "scale-in": "scaleIn 0.18s ease-out",
        "pulse-soft": "pulseSoft 2s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.97)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        pulseSoft: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
    },
  },
  plugins: [],
};